name: poet
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

  #상태관리
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3

  #ML Kit
  camera: ^0.11.2
  google_mlkit_image_labeling: ^0.14.1
  google_mlkit_commons: ^0.11.0

  #Firebase
  firebase_core: ^4.2.0
  firebase_ai: ^3.4.0

  cupertino_icons: ^1.0.8

dev_dependencies:

  build_runner: ^2.7.1
  riverpod_generator: ^3.0.3

  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  

